#ifndef SQL_DATABASE_MANAGER_GLOBAL_H
#define SQL_DATABASE_MANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SQL_DATABASE_MANAGER_LIBRARY)
#  define SQL_DATABASE_MANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SQL_DATABASE_MANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SQL_DATABASE_MANAGER_GLOBAL_H
