-- MySQL Script generated by MySQL Workbench
-- 03/03/16 23:26:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`MICD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MICD` (
  `id` INT NOT NULL COMMENT '',
  `Name` VARCHAR(45) NULL COMMENT '',
  `Path` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Models`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Models` (
  `id` INT NOT NULL COMMENT '',
  `Name` VARCHAR(45) NULL COMMENT '',
  `Occurence` INT NULL COMMENT '',
  `Micd` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `Micd`)  COMMENT '',
  INDEX `Micd_idx` (`Micd` ASC)  COMMENT '',
  CONSTRAINT `Micd`
    FOREIGN KEY (`Micd`)
    REFERENCES `mydb`.`MICD` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Data_Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Data_Type` (
  `id` INT NOT NULL COMMENT '',
  `Name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Unit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Unit` (
  `id` INT NOT NULL COMMENT '',
  `Name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Com_Format`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Com_Format` (
  `id` INT NOT NULL COMMENT '',
  `Name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Com_Mode`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Com_Mode` (
  `id` INT NOT NULL COMMENT '',
  `Name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Interface_level`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Interface_level` (
  `id` INT NOT NULL COMMENT '',
  `Name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`status` (
  `id` INT NOT NULL COMMENT '',
  `Name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ports_IN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ports_IN` (
  `id` INT NOT NULL COMMENT '',
  `Name` VARCHAR(45) NOT NULL COMMENT '',
  `Type` INT NOT NULL COMMENT '',
  `Unit` INT NULL COMMENT '',
  `Description` VARCHAR(45) NULL COMMENT '',
  `Convention` VARCHAR(45) NULL COMMENT '',
  `Dim1` INT NOT NULL COMMENT '',
  `Dim2` INT NOT NULL COMMENT '',
  `Com_Format` INT NULL COMMENT '',
  `Com_Mode` INT NULL COMMENT '',
  `From` VARCHAR(45) NULL COMMENT '',
  `Refresh` INT NULL COMMENT '',
  `Min` DECIMAL(10,0) NULL COMMENT '',
  `Max` DECIMAL(10,0) NULL COMMENT '',
  `Enum` VARCHAR(45) NULL COMMENT '',
  `Consummed_If` VARCHAR(45) NULL COMMENT '',
  `Aircraft_Signal_Name` VARCHAR(45) NULL COMMENT '',
  `Interface_Level` INT NULL COMMENT '',
  `Status` INT NULL COMMENT '',
  `Inits` DECIMAL(10,0) NULL COMMENT '',
  `Model` INT NOT NULL COMMENT '',
  `Micd` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `Model_idx` (`Model` ASC)  COMMENT '',
  INDEX `Type_idx` (`Type` ASC)  COMMENT '',
  INDEX `Unit_idx` (`Unit` ASC)  COMMENT '',
  INDEX `Com_Format_idx` (`Com_Format` ASC)  COMMENT '',
  INDEX `Com_Mode_idx` (`Com_Mode` ASC)  COMMENT '',
  INDEX `Interface_Level_idx` (`Interface_Level` ASC)  COMMENT '',
  INDEX `Status_idx` (`Status` ASC)  COMMENT '',
  INDEX `Micd_idx` (`Micd` ASC)  COMMENT '',
  CONSTRAINT `Model`
    FOREIGN KEY (`Model`)
    REFERENCES `mydb`.`Models` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Type`
    FOREIGN KEY (`Type`)
    REFERENCES `mydb`.`Data_Type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Unit`
    FOREIGN KEY (`Unit`)
    REFERENCES `mydb`.`Unit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Com_Format`
    FOREIGN KEY (`Com_Format`)
    REFERENCES `mydb`.`Com_Format` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Com_Mode`
    FOREIGN KEY (`Com_Mode`)
    REFERENCES `mydb`.`Com_Mode` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Interface_Level`
    FOREIGN KEY (`Interface_Level`)
    REFERENCES `mydb`.`Interface_level` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Status`
    FOREIGN KEY (`Status`)
    REFERENCES `mydb`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Micd`
    FOREIGN KEY (`Micd`)
    REFERENCES `mydb`.`MICD` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ports_OUT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ports_OUT` (
  `id` INT NOT NULL COMMENT '',
  `Name` VARCHAR(45) NOT NULL COMMENT '',
  `Type` INT NOT NULL COMMENT '',
  `Unit` INT NULL COMMENT '',
  `Description` VARCHAR(45) NULL COMMENT '',
  `Convention` VARCHAR(45) NULL COMMENT '',
  `Dim1` INT NOT NULL COMMENT '',
  `Dim2` INT NOT NULL COMMENT '',
  `Com_Format` INT NULL COMMENT '',
  `Com_Mode` INT NULL COMMENT '',
  `To` VARCHAR(45) NULL COMMENT '',
  `Refresh` VARCHAR(45) NULL COMMENT '',
  `Min` DECIMAL(10,0) NULL COMMENT '',
  `Max` DECIMAL(10,0) NULL COMMENT '',
  `Enum` VARCHAR(45) NULL COMMENT '',
  `Produced_If` VARCHAR(45) NULL COMMENT '',
  `Aircraft_Signal_Name` VARCHAR(45) NULL COMMENT '',
  `Interface_Level` INT NULL COMMENT '',
  `Status` INT NULL COMMENT '',
  `Default_value` DECIMAL(10,0) NULL COMMENT '',
  `Micd` INT NULL COMMENT '',
  `Models_id` INT NOT NULL COMMENT '',
  `Models_Micd` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `Type_idx` (`Type` ASC)  COMMENT '',
  INDEX `Unit_idx` (`Unit` ASC)  COMMENT '',
  INDEX `Com_Format_idx` (`Com_Format` ASC)  COMMENT '',
  INDEX `Com_Mode_idx` (`Com_Mode` ASC)  COMMENT '',
  INDEX `Interface_Level_idx` (`Interface_Level` ASC)  COMMENT '',
  INDEX `Status_idx` (`Status` ASC)  COMMENT '',
  INDEX `Micd_idx` (`Micd` ASC)  COMMENT '',
  INDEX `Models_idx` (`Models_id` ASC)  COMMENT '',
  CONSTRAINT `Type`
    FOREIGN KEY (`Type`)
    REFERENCES `mydb`.`Data_Type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Unit`
    FOREIGN KEY (`Unit`)
    REFERENCES `mydb`.`Unit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Com_Format`
    FOREIGN KEY (`Com_Format`)
    REFERENCES `mydb`.`Com_Format` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Com_Mode`
    FOREIGN KEY (`Com_Mode`)
    REFERENCES `mydb`.`Com_Mode` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Interface_Level`
    FOREIGN KEY (`Interface_Level`)
    REFERENCES `mydb`.`Interface_level` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Status`
    FOREIGN KEY (`Status`)
    REFERENCES `mydb`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Micd`
    FOREIGN KEY (`Micd`)
    REFERENCES `mydb`.`MICD` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `Models`
    FOREIGN KEY (`Models_id`)
    REFERENCES `mydb`.`Models` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Signals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Signals` (
  `Id` INT NOT NULL COMMENT '',
  `Name` VARCHAR(45) NULL COMMENT '',
  `Init` DECIMAL(10,0) NULL COMMENT '',
  PRIMARY KEY (`Id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Operators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Operators` (
  `id` INT NOT NULL COMMENT '',
  `Name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`flot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`flot` (
  `id` INT NOT NULL COMMENT '',
  `filename` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Connexions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Connexions` (
  `id` INT NOT NULL COMMENT '',
  `Producer_model` INT NULL COMMENT '',
  `Producer_port` INT NULL COMMENT '',
  `Producer_operator` INT NULL COMMENT '',
  `Producer_tab` VARCHAR(45) NULL COMMENT '',
  `Signal` INT NULL COMMENT '',
  `Consummer_model` INT NULL COMMENT '',
  `Consummer_port` INT NULL COMMENT '',
  `Consummer_operator` INT NULL COMMENT '',
  `Consummer_tab` VARCHAR(45) NULL COMMENT '',
  `flot_id` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `Producer_model_idx` (`Producer_model` ASC)  COMMENT '',
  INDEX `Consummer_model_idx` (`Consummer_model` ASC)  COMMENT '',
  INDEX `Consummer_operator_idx` (`Consummer_operator` ASC)  COMMENT '',
  INDEX `Consummer_port_idx` (`Consummer_port` ASC)  COMMENT '',
  INDEX `Signal_idx` (`Signal` ASC)  COMMENT '',
  INDEX `Producer_opertor_idx` (`Producer_operator` ASC)  COMMENT '',
  INDEX `Producer_port_idx` (`Producer_port` ASC)  COMMENT '',
  INDEX `flot_idx` (`flot_id` ASC)  COMMENT '',
  CONSTRAINT `Producer_model`
    FOREIGN KEY (`Producer_model`)
    REFERENCES `mydb`.`Models` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Producer_port`
    FOREIGN KEY (`Producer_port`)
    REFERENCES `mydb`.`Ports_OUT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Producer_opertor`
    FOREIGN KEY (`Producer_operator`)
    REFERENCES `mydb`.`Operators` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Signal`
    FOREIGN KEY (`Signal`)
    REFERENCES `mydb`.`Signals` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Consummer_port`
    FOREIGN KEY (`Consummer_port`)
    REFERENCES `mydb`.`Ports_IN` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Consummer_operator`
    FOREIGN KEY (`Consummer_operator`)
    REFERENCES `mydb`.`Operators` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Consummer_model`
    FOREIGN KEY (`Consummer_model`)
    REFERENCES `mydb`.`Models` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `flot`
    FOREIGN KEY (`flot_id`)
    REFERENCES `mydb`.`flot` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EQUIPMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EQUIPMENT` (
  `id` INT NOT NULL COMMENT '',
  `Name` VARCHAR(45) NULL COMMENT '',
  `Description` VARCHAR(45) NULL COMMENT '',
  `Type` VARCHAR(45) NULL COMMENT '',
  `EMC Protection` VARCHAR(45) NULL COMMENT '',
  `Zone` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ACICD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ACICD` (
  `id` INT NOT NULL COMMENT '',
  `Name` VARCHAR(45) NULL COMMENT '',
  `Path` VARCHAR(45) NULL COMMENT '',
  `Micd` INT NULL COMMENT '',
  `Equipment` INT NULL COMMENT '',
  `Version` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `Equipment_idx` (`Equipment` ASC)  COMMENT '',
  CONSTRAINT `Equipment`
    FOREIGN KEY (`Equipment`)
    REFERENCES `mydb`.`EQUIPMENT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`jointure_MICD_ACICD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`jointure_MICD_ACICD` (
  `micd` INT NOT NULL COMMENT '',
  `acicd` INT NULL COMMENT '',
  PRIMARY KEY (`micd`)  COMMENT '',
  INDEX `acicd_idx` (`acicd` ASC)  COMMENT '',
  CONSTRAINT `micd`
    FOREIGN KEY (`micd`)
    REFERENCES `mydb`.`MICD` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `acicd`
    FOREIGN KEY (`acicd`)
    REFERENCES `mydb`.`ACICD` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Connector_Pin_Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Connector_Pin_Role` (
  `id` INT NOT NULL COMMENT '',
  `Name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Connector_Line_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Connector_Line_type` (
  `id` INT NOT NULL COMMENT '',
  `Name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Connection_Name`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Connection_Name` (
  `id` INT NOT NULL COMMENT '',
  `Name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CONNECTOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CONNECTOR` (
  `id` INT NOT NULL COMMENT '',
  `Equipment` INT NULL COMMENT '',
  `ACICD` INT NULL COMMENT '',
  `Type` VARCHAR(45) NULL COMMENT '',
  `Name` VARCHAR(45) NULL COMMENT '',
  `Pin` VARCHAR(45) NULL COMMENT '',
  `Pin_Role` INT NULL COMMENT '',
  `Connection_Name` INT NULL COMMENT '',
  `Line_Type` INT NULL COMMENT '',
  `Speed` INT NULL COMMENT '',
  `NetworkId` VARCHAR(3) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `Equipment_idx` (`Equipment` ASC)  COMMENT '',
  INDEX `ACICD_idx` (`ACICD` ASC)  COMMENT '',
  INDEX `Pin_Role_idx` (`Pin_Role` ASC)  COMMENT '',
  INDEX `Line_Type_idx` (`Line_Type` ASC)  COMMENT '',
  INDEX `Connection_Name_idx` (`Connection_Name` ASC)  COMMENT '',
  CONSTRAINT `Equipment`
    FOREIGN KEY (`Equipment`)
    REFERENCES `mydb`.`EQUIPMENT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ACICD`
    FOREIGN KEY (`ACICD`)
    REFERENCES `mydb`.`ACICD` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Pin_Role`
    FOREIGN KEY (`Pin_Role`)
    REFERENCES `mydb`.`Connector_Pin_Role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Line_Type`
    FOREIGN KEY (`Line_Type`)
    REFERENCES `mydb`.`Connector_Line_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Connection_Name`
    FOREIGN KEY (`Connection_Name`)
    REFERENCES `mydb`.`Connection_Name` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AFDX_port_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AFDX_port_type` (
  `id` INT NOT NULL COMMENT '',
  `Type` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AFDX_port_characteristic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AFDX_port_characteristic` (
  `id` INT NOT NULL COMMENT '',
  `characteristic` VARCHAR(9) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AFDX_port_transmission_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AFDX_port_transmission_type` (
  `id` INT NOT NULL COMMENT '',
  `Name` VARCHAR(9) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AFDX_TX_port`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AFDX_TX_port` (
  `id` INT NOT NULL COMMENT '',
  `Identifier` INT NULL COMMENT '',
  `Master_Name` VARCHAR(45) NULL COMMENT '',
  `Type` INT NULL COMMENT '',
  `characteristic` INT NULL COMMENT '',
  `transmission_type` INT NULL COMMENT '',
  `EQUIPMENT` INT NOT NULL COMMENT '',
  `Src_IP_Adress` VARCHAR(15) NULL COMMENT '',
  `Dest_IP_Adress` VARCHAR(15) NULL COMMENT '',
  `Src_UDP_Adress` INT(1) NULL COMMENT '',
  `Dest_UDP_Adress` INT(1) NULL COMMENT '',
  `Buffersize` INT(1) NULL COMMENT '',
  `IP_frag_allowed` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `Type_idx` (`Type` ASC)  COMMENT '',
  INDEX `transmission_type_idx` (`transmission_type` ASC)  COMMENT '',
  INDEX `fk_AFDX_TX_port_EQUIPMENT1_idx` (`EQUIPMENT` ASC)  COMMENT '',
  CONSTRAINT `Type`
    FOREIGN KEY (`Type`)
    REFERENCES `mydb`.`AFDX_port_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `characteristic`
    FOREIGN KEY ()
    REFERENCES `mydb`.`AFDX_port_characteristic` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `transmission_type`
    FOREIGN KEY (`transmission_type`)
    REFERENCES `mydb`.`AFDX_port_transmission_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AFDX_TX_port_EQUIPMENT1`
    FOREIGN KEY (`EQUIPMENT`)
    REFERENCES `mydb`.`EQUIPMENT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AFDX_VL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AFDX_VL` (
  `id` INT NOT NULL COMMENT '',
  `VL_name` VARCHAR(45) NULL COMMENT '',
  `VL_Identifier` SMALLINT(6) NULL COMMENT '',
  `Network_sel` VARCHAR(3) NULL COMMENT '',
  `BAG` TINYINT(4) NULL COMMENT '',
  `MAX_frame_size` SMALLINT(6) NULL COMMENT '',
  `Sub_VL_Number` INT(1) NULL COMMENT '',
  `Sub_VL_Identifier` INT(1) NULL COMMENT '',
  `TX_port` INT NULL COMMENT '',
  `AFDX_VLcol` VARCHAR(45) NULL COMMENT '',
  `TX_Equipment` INT NOT NULL COMMENT '',
  `TX_port` INT NOT NULL COMMENT '',
  `TX_Connector` INT NOT NULL COMMENT '',
  `IC_active` TINYINT(1) NULL COMMENT '',
  `Skew_max` INT(2) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `TX_Equipment_idx` (`TX_Equipment` ASC)  COMMENT '',
  INDEX `fk_AFDX_VL_AFDX_TX_port1_idx` (`TX_port` ASC)  COMMENT '',
  INDEX `fk_AFDX_VL_CONNECTOR1_idx` (`TX_Connector` ASC)  COMMENT '',
  CONSTRAINT `TX_Equipment`
    FOREIGN KEY (`TX_Equipment`)
    REFERENCES `mydb`.`EQUIPMENT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AFDX_VL_AFDX_TX_port1`
    FOREIGN KEY (`TX_port`)
    REFERENCES `mydb`.`AFDX_TX_port` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AFDX_VL_CONNECTOR1`
    FOREIGN KEY (`TX_Connector`)
    REFERENCES `mydb`.`CONNECTOR` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AFDX_application`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AFDX_application` (
  `id` INT NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `type` VARCHAR(45) NULL COMMENT '',
  `description` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AFDX_Message_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AFDX_Message_type` (
  `id` INT NOT NULL COMMENT '',
  `message_type` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AFDX_MESSAGE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AFDX_MESSAGE` (
  `id` INT NOT NULL COMMENT '',
  `AFDX_application_id` INT NOT NULL COMMENT '',
  `AFDX_VL_id` INT NOT NULL COMMENT '',
  `AFDX_TX_port_id` INT NOT NULL COMMENT '',
  `description` VARCHAR(45) NULL COMMENT '',
  `ref_doc` VARCHAR(45) NULL COMMENT '',
  `type` VARCHAR(45) NULL COMMENT '',
  `AFDX_Message_type_id` INT NOT NULL COMMENT '',
  `Protocol_type` VARCHAR(45) NULL COMMENT '',
  `Lenght` INT(1) NULL COMMENT '',
  `Global_spare` INT(1) NULL COMMENT '',
  `Transmission_rate` INT(1) NULL COMMENT '',
  `Port_refresh_rate` INT(1) NULL COMMENT '',
  `AFDX_MESSAGEcol` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_AFDX_MESSAGE_AFDX_application1_idx` (`AFDX_application_id` ASC)  COMMENT '',
  INDEX `fk_AFDX_MESSAGE_AFDX_VL1_idx` (`AFDX_VL_id` ASC)  COMMENT '',
  INDEX `fk_AFDX_MESSAGE_AFDX_TX_port1_idx` (`AFDX_TX_port_id` ASC)  COMMENT '',
  INDEX `fk_AFDX_MESSAGE_AFDX_Message_type1_idx` (`AFDX_Message_type_id` ASC)  COMMENT '',
  CONSTRAINT `fk_AFDX_MESSAGE_AFDX_application1`
    FOREIGN KEY (`AFDX_application_id`)
    REFERENCES `mydb`.`AFDX_application` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AFDX_MESSAGE_AFDX_VL1`
    FOREIGN KEY (`AFDX_VL_id`)
    REFERENCES `mydb`.`AFDX_VL` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AFDX_MESSAGE_AFDX_TX_port1`
    FOREIGN KEY (`AFDX_TX_port_id`)
    REFERENCES `mydb`.`AFDX_TX_port` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AFDX_MESSAGE_AFDX_Message_type1`
    FOREIGN KEY (`AFDX_Message_type_id`)
    REFERENCES `mydb`.`AFDX_Message_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AFDX_FS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AFDX_FS` (
  `id` INT NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `description` VARCHAR(45) NULL COMMENT '',
  `adress_in_message` INT(1) NULL COMMENT '',
  `AFDX_MESSAGE_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_AFDX_FS_AFDX_MESSAGE1_idx` (`AFDX_MESSAGE_id` ASC)  COMMENT '',
  CONSTRAINT `fk_AFDX_FS_AFDX_MESSAGE1`
    FOREIGN KEY (`AFDX_MESSAGE_id`)
    REFERENCES `mydb`.`AFDX_MESSAGE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AFDX_FDS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AFDX_FDS` (
  `id` INT NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `description` VARCHAR(45) NULL COMMENT '',
  `lenght` INT(1) NULL COMMENT '',
  `spare_lenght` INT(1) NULL COMMENT '',
  `adress_in_message` INT(1) NULL COMMENT '',
  `AFDX_MESSAGE_id` INT NOT NULL COMMENT '',
  `AFDX_FS_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_AFDX_FDS_AFDX_MESSAGE1_idx` (`AFDX_MESSAGE_id` ASC)  COMMENT '',
  INDEX `fk_AFDX_FDS_AFDX_FS1_idx` (`AFDX_FS_id` ASC)  COMMENT '',
  CONSTRAINT `fk_AFDX_FDS_AFDX_MESSAGE1`
    FOREIGN KEY (`AFDX_MESSAGE_id`)
    REFERENCES `mydb`.`AFDX_MESSAGE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AFDX_FDS_AFDX_FS1`
    FOREIGN KEY (`AFDX_FS_id`)
    REFERENCES `mydb`.`AFDX_FS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AFDX_signal_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AFDX_signal_type` (
  `id` INT NOT NULL COMMENT '',
  `type` VARCHAR(15) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AFDX_signal_BOOL_caract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AFDX_signal_BOOL_caract` (
  `id` INT NOT NULL COMMENT '',
  `TRUE_def` VARCHAR(10) NULL COMMENT '',
  `FALSE_def` VARCHAR(10) NULL COMMENT '',
  `TRUE_state` TINYINT(1) NULL COMMENT '',
  `FALSE_state` TINYINT(1) NULL COMMENT '',
  `Logic` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AFDX_signal_String_caract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AFDX_signal_String_caract` (
  `id` INT NOT NULL COMMENT '',
  `lenght` VARCHAR(45) NULL COMMENT '',
  `format` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AFDX_Enumerate_caract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AFDX_Enumerate_caract` (
  `id` INT NOT NULL COMMENT '',
  `state` VARCHAR(45) NULL COMMENT '',
  `associated_value` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Coding_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Coding_type` (
  `id` INT NOT NULL COMMENT '',
  `type` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AFDX_signal_INT_caract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AFDX_signal_INT_caract` (
  `id` INT NOT NULL COMMENT '',
  `min` INT NULL COMMENT '',
  `max` INT NULL COMMENT '',
  `Unit_id` INT NOT NULL COMMENT '',
  `accuray` INT NULL COMMENT '',
  `Coding_type_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_AFDX_signal_INT_caract_Unit1_idx` (`Unit_id` ASC)  COMMENT '',
  INDEX `fk_AFDX_signal_INT_caract_Coding_type1_idx` (`Coding_type_id` ASC)  COMMENT '',
  CONSTRAINT `fk_AFDX_signal_INT_caract_Unit1`
    FOREIGN KEY (`Unit_id`)
    REFERENCES `mydb`.`Unit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AFDX_signal_INT_caract_Coding_type1`
    FOREIGN KEY (`Coding_type_id`)
    REFERENCES `mydb`.`Coding_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AFDX_signal_opaque_caract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AFDX_signal_opaque_caract` (
  `id` INT NOT NULL COMMENT '',
  `size` INT NULL COMMENT '',
  `lenght` INT(1) NULL COMMENT '',
  `IOM_corresponding_label` INT(1) NULL COMMENT '',
  `Corresponding_label` INT(1) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AFDX_signal_FLOAT_caract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AFDX_signal_FLOAT_caract` (
  `id` INT NOT NULL COMMENT '',
  `min` FLOAT NULL COMMENT '',
  `max` FLOAT NULL COMMENT '',
  `Unit_id` INT NOT NULL COMMENT '',
  `Coding_type_id` INT NOT NULL COMMENT '',
  `accuracy` FLOAT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_AFDX_signal_FLOAT_caract_Unit1_idx` (`Unit_id` ASC)  COMMENT '',
  INDEX `fk_AFDX_signal_FLOAT_caract_Float_Coding_type1_idx` (`Coding_type_id` ASC)  COMMENT '',
  CONSTRAINT `fk_AFDX_signal_FLOAT_caract_Unit1`
    FOREIGN KEY (`Unit_id`)
    REFERENCES `mydb`.`Unit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AFDX_signal_FLOAT_caract_Float_Coding_type1`
    FOREIGN KEY (`Coding_type_id`)
    REFERENCES `mydb`.`Coding_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AFDX_signal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AFDX_signal` (
  `id` INT NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `AFDX_signal_type_id` INT NOT NULL COMMENT '',
  `description` VARCHAR(45) NULL COMMENT '',
  `ref_doc` VARCHAR(45) NULL COMMENT '',
  `nb_of_bit` INT(1) NULL COMMENT '',
  `adress` VARCHAR(45) NULL COMMENT '',
  `position` INT(1) NULL COMMENT '',
  `AFDX_signal_BOOL_caract_id` INT NULL COMMENT '',
  `AFDX_signal_String_carac_id` INT NULL COMMENT '',
  `AFDX_Enumerate_caract_id` INT NULL COMMENT '',
  `AFDX_signal_FLOAT_caract_id` INT NULL COMMENT '',
  `AFDX_signal_INT_caract_id` INT NULL COMMENT '',
  `AFDX_signal_opaque_caract_id` INT NULL COMMENT '',
  `AFDX_MESSAGE_id` INT NOT NULL COMMENT '',
  `AFDX_FDS_id` INT NOT NULL COMMENT '',
  `AFDX_FS_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_AFDX_signal_AFDX_signal_type1_idx` (`AFDX_signal_type_id` ASC)  COMMENT '',
  INDEX `fk_AFDX_signal_AFDX_signal_BOOL_caract1_idx` (`AFDX_signal_BOOL_caract_id` ASC)  COMMENT '',
  INDEX `fk_AFDX_signal_AFDX_signal_String_carac1_idx` (`AFDX_signal_String_carac_id` ASC)  COMMENT '',
  INDEX `fk_AFDX_signal_AFDX_Enumerate_caract1_idx` (`AFDX_Enumerate_caract_id` ASC)  COMMENT '',
  INDEX `fk_AFDX_signal_AFDX_signal_INT_caract1_idx` (`AFDX_signal_INT_caract_id` ASC)  COMMENT '',
  INDEX `fk_AFDX_signal_AFDX_signal_opaque_caract1_idx` (`AFDX_signal_opaque_caract_id` ASC)  COMMENT '',
  INDEX `fk_AFDX_signal_AFDX_signal_FLOAT_caract1_idx` (`AFDX_signal_FLOAT_caract_id` ASC)  COMMENT '',
  INDEX `fk_AFDX_signal_AFDX_MESSAGE1_idx` (`AFDX_MESSAGE_id` ASC)  COMMENT '',
  INDEX `fk_AFDX_signal_AFDX_FDS1_idx` (`AFDX_FDS_id` ASC)  COMMENT '',
  INDEX `fk_AFDX_signal_AFDX_FS1_idx` (`AFDX_FS_id` ASC)  COMMENT '',
  CONSTRAINT `fk_AFDX_signal_AFDX_signal_type1`
    FOREIGN KEY (`AFDX_signal_type_id`)
    REFERENCES `mydb`.`AFDX_signal_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AFDX_signal_AFDX_signal_BOOL_caract1`
    FOREIGN KEY (`AFDX_signal_BOOL_caract_id`)
    REFERENCES `mydb`.`AFDX_signal_BOOL_caract` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AFDX_signal_AFDX_signal_String_carac1`
    FOREIGN KEY (`AFDX_signal_String_carac_id`)
    REFERENCES `mydb`.`AFDX_signal_String_caract` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AFDX_signal_AFDX_Enumerate_caract1`
    FOREIGN KEY (`AFDX_Enumerate_caract_id`)
    REFERENCES `mydb`.`AFDX_Enumerate_caract` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AFDX_signal_AFDX_signal_INT_caract1`
    FOREIGN KEY (`AFDX_signal_INT_caract_id`)
    REFERENCES `mydb`.`AFDX_signal_INT_caract` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AFDX_signal_AFDX_signal_opaque_caract1`
    FOREIGN KEY (`AFDX_signal_opaque_caract_id`)
    REFERENCES `mydb`.`AFDX_signal_opaque_caract` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AFDX_signal_AFDX_signal_FLOAT_caract1`
    FOREIGN KEY (`AFDX_signal_FLOAT_caract_id`)
    REFERENCES `mydb`.`AFDX_signal_FLOAT_caract` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AFDX_signal_AFDX_MESSAGE1`
    FOREIGN KEY (`AFDX_MESSAGE_id`)
    REFERENCES `mydb`.`AFDX_MESSAGE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AFDX_signal_AFDX_FDS1`
    FOREIGN KEY (`AFDX_FDS_id`)
    REFERENCES `mydb`.`AFDX_FDS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AFDX_signal_AFDX_FS1`
    FOREIGN KEY (`AFDX_FS_id`)
    REFERENCES `mydb`.`AFDX_FS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AFDX_RX_port`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AFDX_RX_port` (
  `id` INT NOT NULL COMMENT '',
  `Identifier` INT NULL COMMENT '',
  `Master_Name` VARCHAR(45) NULL COMMENT '',
  `Type` INT NULL COMMENT '',
  `characteristic` INT NULL COMMENT '',
  `transmission_type` INT NULL COMMENT '',
  `EQUIPMENT` INT NOT NULL COMMENT '',
  `Dest_IP_Adress` VARCHAR(15) NULL COMMENT '',
  `Dest_UDP_Adress` INT(1) NULL COMMENT '',
  `Buffersize` INT(1) NULL COMMENT '',
  `IP_frag_allowed` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `Type_idx` (`Type` ASC)  COMMENT '',
  INDEX `transmission_type_idx` (`transmission_type` ASC)  COMMENT '',
  INDEX `fk_AFDX_TX_port_EQUIPMENT1_idx` (`EQUIPMENT` ASC)  COMMENT '',
  CONSTRAINT `Type0`
    FOREIGN KEY (`Type`)
    REFERENCES `mydb`.`AFDX_port_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `characteristic0`
    FOREIGN KEY ()
    REFERENCES `mydb`.`AFDX_port_characteristic` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `transmission_type0`
    FOREIGN KEY (`transmission_type`)
    REFERENCES `mydb`.`AFDX_port_transmission_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AFDX_TX_port_EQUIPMENT10`
    FOREIGN KEY (`EQUIPMENT`)
    REFERENCES `mydb`.`EQUIPMENT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
